version: "3"
services:
  poetry-contracts:
    build: ../poetry-contracts
    ports:
      - "8545:8545"
    environment:
      - MNEMONIC=squirrel march broom strong kick blast unique team song song assist million
      - INFURAKEY=https://rinkeby.infura.io/v3/df4de1f306044440bf0e4843d8ff667b
      - NETWORK=development
      - ENV=DEVELOPMENT
    volumes:
    - ./appdata:/appdata
    networks:
      - blockchain
      - ui
  poetry-system:
    build: ../poetry-system
    ports:
    - "8080:8080"
    depends_on:
    - mongo
    - poetry-contracts
    environment:
      - MONGO_DB_URL=mongodb://mongo:27017/poetry
      - ENV=DEVELOPMENT
    volumes:
    - ./appdata:/appdata
    networks:
      - database
      - ui
  poetry-payments:
    build: ../poetry-payments
    ports: 
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MATIC_URL=https://gasstation-mainnet.matic.network
      - ETHEREUM_USD_URL=https://api.coingecko.com/api/v3/coins/ethereum/market_chart?vs_currency=usd&days=0
      - MONGO_DB_URL=mongodb://mongo:27017/poetry
      - ENV=DEVELOPMENT
      - STRIPE_API_KEY=sk_test_51ITbKnDJuxMGVHCqOBv9g2HuCwRqfXiuB332SHglYEcAiRICHtJvZSD1in5rFbSviTgW417Z6xWGTICKucrzUHuE00OKaXv2Fd
      - STRIPE_WEBHOOK_SECRET=whsec_GwXzsyvkroa3oZ91wswMafWXVV7WwMDP
    volumes:
      - ./appdata:/appdata
    networks:
      - database
      - payments
      - ui
  poetry-api:
    build: ../poetry-api
    ports: 
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      - MONGO_DB_URL=mongodb://mongo:27017/poetry
      - ENV=DEVELOPMENT
      - PROVIDER=http://poetry-contracts:8545
      - MNEMONIC=squirrel march broom strong kick blast unique team song song assist million
      - GAS_LIMIT=4712388
      - POETRY_PAYMENTS_URL:http://poetry-payments:5000
      - STRIPE_API_KEY=sk_test_51ITbKnDJuxMGVHCqOBv9g2HuCwRqfXiuB332SHglYEcAiRICHtJvZSD1in5rFbSviTgW417Z6xWGTICKucrzUHuE00OKaXv2Fd
    volumes:
      - ./appdata:/appdata
    networks:
      - database
      - payments
      - blockchain
      - ui
  poetry-ui:
    build: ../poetry-ui
    ports:
      - "3000:3000"
    depends_on:
      - poetry-system
      - poetry-payments
      - poetry-api
    environment:
      - REACT_APP_POETRY_SYSTEM_URL=http://localhost:8080
    networks:
      - ui
  mongo:
    image: mongo
    ports:
    - "27017:27017"
    networks:
      - database
networks:
  database:
    driver: bridge
  payments:
    driver: bridge
  blockchain:
    driver: bridge
  ui:
    driver: bridge
  