version: "3"
services:
  poetry-contracts:
    build: ../poetry-contracts
    ports:
      - "8545:8545"
    volumes:
    - ./appdata:/appdata
  poetry-system:
    build: ../poetry-system
    ports:
    - "8080:8080"
    depends_on:
    - mongo
    - poetry-contracts
    environment:
      - MONGO_DB_URL=mongodb://mongo:27017/poetry
      - ENV=DEVELOPMENT
      - PORT=8080
    volumes:
    - ./appdata:/appdata
    networks:
      - database
    links:
      - mongo
  poetry-payments:
    build: ../poetry-payments
    ports: 
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MATIC_URL=https://gasstation-mainnet.matic.network
      - ETHEREUM_URL=https://data-api.defipulse.com/api/v1/egs/api/ethgasAPI.json?api-key=6d52d76f9864c854c36d043d987ba171c5a86ff7205cd12ff8509a7be07b
      - ETHEREUM_USD_URL=https://api.coingecko.com/api/v3/coins/ethereum/market_chart?vs_currency=usd&days=0
      - PROVIDER=http://localhost:8545
    volumes:
      - ./appdata:/appdata
    networks:
      - database
      - payments
    links:
      - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"
    networks:
      - database
networks:
  database:
    driver: bridge
  payments:
    driver: bridge
  